/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-03-26 14:48:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Footer</title>\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" />\r\n");
      out.write("<!-- Google Fonts Roboto -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap\" />\r\n");

String url = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
		+ request.getContextPath();

      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	<footer class=\"text-center text-lg-start bg-secondary\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Section: Links  -->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container-fluid text-center text-md-start pt-3\">\r\n");
      out.write("			<!-- Grid row -->\r\n");
      out.write("			<div class=\"row pt-5\">\r\n");
      out.write("				<!-- Grid column -->\r\n");
      out.write("				<div class=\"col-md-3 col-lg-4 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("					<!-- Content -->\r\n");
      out.write("					<h6 class=\"text-uppercase fw-bold mb-4\">\r\n");
      out.write("						<i class=\"fas fa-gem me-3\"></i>FAM TWEN\r\n");
      out.write("					</h6>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"fas fa-phone me-3\"></i> Tổng đài CSKH: 19008068\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"fas fa-envelope me-3\"></i> Email: cskh@famtwen.com\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						Fam Twen chúng tôi, cam kết cung cấp dịch vụ tốt nhất có thể, luôn lắng nghe và đáp\r\n");
      out.write("						ứng mọi nhu cầu của khách hàng một cách nhanh chóng và hiệu quả nhất. Chúng tôi tin\r\n");
      out.write("						rằng, mối quan hệ với khách hàng không chỉ là về việc bán hàng, mà còn là về việc\r\n");
      out.write("						xây dựng niềm tin và sự tin tưởng về sau.\r\n");
      out.write("						<br>\r\n");
      out.write("						Chính vì vậy, hãy đến với Fam twen và trải nghiệm sự khác biệt mà giá trị chúng tôi\r\n");
      out.write("						mang lại cho bạn. Chúng tôi sẽ luôn ở đây, sẵn sàng phục vụ và đồng hành cùng bạn\r\n");
      out.write("						trên mọi hành trình của bạn.\r\n");
      out.write("					</p>\r\n");
      out.write("\r\n");
      out.write("					<!--Grid column-->\r\n");
      out.write("					<div class=\"col-auto\">\r\n");
      out.write("						<p class=\"pt-2 m-0\">\r\n");
      out.write("							<strong>ĐĂNG KÝ NHẬN TIN</strong>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!--Grid column-->\r\n");
      out.write("					<div class=\"row d-flex\">\r\n");
      out.write("						<!--Grid column-->\r\n");
      out.write("						<div data-mdb-input-init class=\"col-md-8 col-8\">\r\n");
      out.write("							<!-- Email input -->\r\n");
      out.write("							<div class=\"form-outline\">\r\n");
      out.write("								<input type=\"email\" id=\"form5Example26\" class=\"form-control\" />\r\n");
      out.write("								<label class=\"form-label\" for=\"form5Example26\">Email address</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!--Grid column-->\r\n");
      out.write("						<div class=\"col-auto mb-2\">\r\n");
      out.write("							<!-- Submit button -->\r\n");
      out.write("							<button data-mdb-ripple-init type=\"submit\" class=\"btn btn-primary\">Đăng ký</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						<hr>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("				<!-- Grid column -->\r\n");
      out.write("				<div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-3\">\r\n");
      out.write("					<!-- Links -->\r\n");
      out.write("					<h6 class=\"text-uppercase fw-bold mb-4\">HỖ TRỢ KHÁCH HÀNG</h6>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">Chính sách đổi hàng và bảo hành</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">Chính sách Membership</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">Chính sách ưu đãi sinh nhật</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">Chính sách bảo mật</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">Chính sách giao hàng tận nơi</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">Chính sách khuyến mãi đi kèm</a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("				<!-- Grid column -->\r\n");
      out.write("				<div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-3\">\r\n");
      out.write("					<!-- Links -->\r\n");
      out.write("					<h6 class=\"text-uppercase fw-bold mb-4\">HỆ THỐNG CỬA HÀNG</h6>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">|Store 1: Bông Trang, H.Xuyên Mộc, BRVT</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">|Store 2: Bùi Đình Túy ,Bình Thạnh, HCM</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">|Store 3: Thảo Điền, TP.Thủ Đức, HCM</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">|Store 4: Linh Trung, TP.Thủ Đức, HCM</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">|Store 5: Phước Long B, TP.Thủ Đức, HCM</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">|Store 6: Bến Nghé, Q.1, HCM</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">|Store 7: Nguyễn Cư Trinh, Q.1, HCM</a>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("				<!-- Grid column -->\r\n");
      out.write("				<div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-3\">\r\n");
      out.write("					<!-- Links -->\r\n");
      out.write("					<h6 class=\"text-uppercase fw-bold mb-4\">FANPAGE CHÚNG TÔI</h6>\r\n");
      out.write("					<p>\r\n");
      out.write("						<a href=\"#!\" class=\"text-reset\">Phương Thức Thanh toán</a>\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"fab fa-cc-visa me-3\"></i> Visa Card\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"fab fa-cc-mastercard me-3\"></i> Master Card\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"far fa-credit-card me-3\"></i> Credit Card\r\n");
      out.write("					</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<i class=\"fas fa-hand-holding-dollar me-3\"></i> Cash\r\n");
      out.write("					</p>\r\n");
      out.write("					<!--Grid column-->\r\n");
      out.write("\r\n");
      out.write("					<p class=\"pt-2\">\r\n");
      out.write("						<b>KẾT NỐI VỚI CHÚNG TÔI</b>\r\n");
      out.write("					</p>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"row d-flex align-items-center m-0 p-0\">\r\n");
      out.write("						<!-- Facebook -->\r\n");
      out.write("						<a data-mdb-ripple-init class=\"btn text-white btn-floating mx-1\"\r\n");
      out.write("							style=\"background-color: #3b5998;\" href=\"#!\" role=\"button\">\r\n");
      out.write("							<i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("\r\n");
      out.write("						<!-- Twitter -->\r\n");
      out.write("						<a data-mdb-ripple-init class=\"btn text-white btn-floating mx-1\"\r\n");
      out.write("							style=\"background-color: #55acee;\" href=\"#!\" role=\"button\">\r\n");
      out.write("							<i class=\"fab fa-twitter\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("\r\n");
      out.write("						<!-- Google -->\r\n");
      out.write("						<a data-mdb-ripple-init class=\"btn text-white btn-floating mx-1\"\r\n");
      out.write("							style=\"background-color: #dd4b39;\" href=\"#!\" role=\"button\">\r\n");
      out.write("							<i class=\"fab fa-google\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("\r\n");
      out.write("						<!-- Instagram -->\r\n");
      out.write("						<a data-mdb-ripple-init class=\"btn text-white btn-floating mx-1\"\r\n");
      out.write("							style=\"background-color: #ac2bac;\" href=\"#!\" role=\"button\">\r\n");
      out.write("							<i class=\"fab fa-instagram\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("\r\n");
      out.write("						<!-- Linkedin -->\r\n");
      out.write("						<a data-mdb-ripple-init class=\"btn text-white btn-floating mx-1\"\r\n");
      out.write("							style=\"background-color: #0082ca;\" href=\"#!\" role=\"button\">\r\n");
      out.write("							<i class=\"fab fa-linkedin-in\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("						<!-- Github -->\r\n");
      out.write("						<a data-mdb-ripple-init class=\"btn text-white btn-floating mx-1\"\r\n");
      out.write("							style=\"background-color: #333333;\" href=\"#!\" role=\"button\">\r\n");
      out.write("							<i class=\"fab fa-github\"></i>\r\n");
      out.write("						</a>\r\n");
      out.write("						<!-- Section: Social media -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Grid column -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Grid row -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Section: Links  -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Copyright -->\r\n");
      out.write("		<div class=\"text-center p-4\" style=\"background-color: rgba(0, 0, 0, 0.05);\">\r\n");
      out.write("			© 2024 Copyright:\r\n");
      out.write("			<a class=\"text-reset fw-bold\" href=\"https://mdbootstrap.com/\">Famtwen.com</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Copyright -->\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
