/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-03-29 07:58:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.KhachHang;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("model.KhachHang");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Fam Twen | Trang chủ</title>\r\n");
      out.write("<!-- Font Awesome -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" />\r\n");
      out.write("<!-- Google Fonts Roboto -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap\" />\r\n");

String url = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
		+ request.getContextPath();

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(url);
      out.write("/css/mdb.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div>\r\n");
      out.write("		<!-- Page content -->\r\n");
      out.write("		<section class=\"container-fluid\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-2 col\">\r\n");
      out.write("\r\n");
      out.write("					<!-- Menu left -->\r\n");
      out.write("					");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menuleft.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-10\">\r\n");
      out.write("					<!-- Product -->\r\n");
      out.write("\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<!-- Carousel wrapper -->\r\n");
      out.write("						<div class=\"carousel slide carousel-fade\" id=\"carouselBasicExample\"\r\n");
      out.write("							data-mdb-ride=\"carousel\" data-mdb-carousel-init>\r\n");
      out.write("							<!-- Indicators -->\r\n");
      out.write("							<div class=\"carousel-indicators\">\r\n");
      out.write("								<button type=\"button\" data-mdb-target=\"#carouselBasicExample\"\r\n");
      out.write("									data-mdb-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("								<button type=\"button\" data-mdb-target=\"#carouselBasicExample\"\r\n");
      out.write("									data-mdb-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("								<button type=\"button\" data-mdb-target=\"#carouselBasicExample\"\r\n");
      out.write("									data-mdb-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<!-- Inner -->\r\n");
      out.write("							<div class=\"carousel-inner\">\r\n");
      out.write("								<!-- Single item -->\r\n");
      out.write("								<div class=\"carousel-item active\">\r\n");
      out.write("									<img src=\"./img/slider/5.png\" class=\"d-block w-100\" alt=\"Sunset Over the City\" />\r\n");
      out.write("									<div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("										<h5>First slide label</h5>\r\n");
      out.write("										<p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<!-- Single item -->\r\n");
      out.write("								<div class=\"carousel-item\">\r\n");
      out.write("									<img src=\"./img/slider/3.png\" class=\"d-block w-100\" alt=\"Canyon at Nigh\" />\r\n");
      out.write("									<div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("										<h5>Second slide label</h5>\r\n");
      out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<!-- Single item -->\r\n");
      out.write("								<div class=\"carousel-item\">\r\n");
      out.write("									<img src=\"./img/slider/2.png\" class=\"d-block w-100\"\r\n");
      out.write("										alt=\"Cliff Above a Stormy Sea\" />\r\n");
      out.write("									<div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("										<h5>Third slide label</h5>\r\n");
      out.write("										<p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- Inner -->\r\n");
      out.write("\r\n");
      out.write("							<!-- Controls -->\r\n");
      out.write("							<button class=\"carousel-control-prev\" type=\"button\"\r\n");
      out.write("								data-mdb-target=\"#carouselBasicExample\" data-mdb-slide=\"prev\">\r\n");
      out.write("								<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("									class=\"visually-hidden\">Previous</span>\r\n");
      out.write("							</button>\r\n");
      out.write("							<button class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("								data-mdb-target=\"#carouselBasicExample\" data-mdb-slide=\"next\">\r\n");
      out.write("								<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("									class=\"visually-hidden\">Next</span>\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Carousel wrapper -->\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"row mt-3\">\r\n");
      out.write("						<div class=\"col-lg-3 mb-4\">\r\n");
      out.write("							<div class=\"card h-100\">\r\n");
      out.write("								<a href=\"#\">\r\n");
      out.write("									<img class=\"card-img-top\" src=\"img/products/1.png\" alt=\"Sản phẩm áo\"\r\n");
      out.write("										height=500rem;>\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<h4 class=\"card-title\">\r\n");
      out.write("										<a href=\"#\">Áo thun Pro-S1</a>\r\n");
      out.write("									</h4>\r\n");
      out.write("									<h5>80.000</h5>\r\n");
      out.write("									<p class=\"card-text\">Sản phẩm thoáng mát, có độ bền tốt, giữ màu sắc tốt.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-footer\">\r\n");
      out.write("									<small class=\"text-muted\">&#9733; &#9733; &#9733; &#9733; &#9734;</small>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-lg-3 mb-4 \">\r\n");
      out.write("							<div class=\"card h-100\">\r\n");
      out.write("								<a href=\"#\">\r\n");
      out.write("									<img class=\"card-img-top\" src=\"img/products/2.png\" alt=\"Sản phẩm áo\"\r\n");
      out.write("										height=500rem;>\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<h4 class=\"card-title\">\r\n");
      out.write("										<a href=\"#\">Suit</a>\r\n");
      out.write("									</h4>\r\n");
      out.write("									<h5>1.050.000</h5>\r\n");
      out.write("									<p class=\"card-text\">Sản phẩm thoáng mát, có độ bền tốt, giữ màu sắc tốt.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-footer\">\r\n");
      out.write("									<small class=\"text-muted\">&#9733; &#9733; &#9733; &#9733; &#9734;</small>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-lg-3 mb-4\">\r\n");
      out.write("							<div class=\"card h-100\">\r\n");
      out.write("								<a href=\"#\">\r\n");
      out.write("									<img class=\"card-img-top\" src=\"img/products/shoe.png\" alt=\"Sản phẩm giày\"\r\n");
      out.write("										height=500rem;>\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<h4 class=\"card-title\">\r\n");
      out.write("										<a href=\"#\">Converse</a>\r\n");
      out.write("									</h4>\r\n");
      out.write("									<h5>2.135.000</h5>\r\n");
      out.write("									<p class=\"card-text\">Sản phẩm trẻ trung, có độ bền tốt, giữ màu sắc tốt.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-footer\">\r\n");
      out.write("									<small class=\"text-muted\">&#9733; &#9733; &#9733; &#9733; &#9734;</small>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-lg-3 mb-4\">\r\n");
      out.write("							<div class=\"card h-100\">\r\n");
      out.write("								<a href=\"#\">\r\n");
      out.write("									<img class=\"card-img-top\" src=\"img/products/4.png\" alt=\"Sản phẩm áo\"\r\n");
      out.write("										height=500rem;>\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<h4 class=\"card-title\">\r\n");
      out.write("										<a href=\"#\">Áo dù</a>\r\n");
      out.write("									</h4>\r\n");
      out.write("									<h5>500.000</h5>\r\n");
      out.write("									<p class=\"card-text\">Form lịch sự, có độ bền tốt, giữ màu sắc tốt.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-footer\">\r\n");
      out.write("									<small class=\"text-muted\">&#9733; &#9733; &#9733; &#9733; &#9734;</small>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-lg-3 mb-4\">\r\n");
      out.write("							<div class=\"card h-100\">\r\n");
      out.write("								<a href=\"#\">\r\n");
      out.write("									<img class=\"card-img-top\" src=\"img/products/dongho.png\" alt=\"Sản phẩm đồng hồ\"\r\n");
      out.write("										height=500rem;>\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<h4 class=\"card-title\">\r\n");
      out.write("										<a href=\"#\">Đồng hồ</a>\r\n");
      out.write("									</h4>\r\n");
      out.write("									<h5>1.200.000</h5>\r\n");
      out.write("									<p class=\"card-text\">Form lịch sự, có độ bền tốt, giữ màu sắc tốt.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-footer\">\r\n");
      out.write("									<small class=\"text-muted\">&#9733; &#9733; &#9733; &#9733; &#9734;</small>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-lg-3 mb-4\">\r\n");
      out.write("							<div class=\"card h-100\">\r\n");
      out.write("								<a href=\"#\">\r\n");
      out.write("									<img class=\"card-img-top\" src=\"img/products/dress.png\" alt=\"Sản phẩm đầm nữ\"\r\n");
      out.write("										height=500rem;>\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<h4 class=\"card-title\">\r\n");
      out.write("										<a href=\"#\">Áo đầm nữ</a>\r\n");
      out.write("									</h4>\r\n");
      out.write("									<h5>1.200.000</h5>\r\n");
      out.write("									<p class=\"card-text\">Váy trắng tinh khiết, lộng lẫy, sang trọng, giữ màu sắc\r\n");
      out.write("										tốt.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-footer\">\r\n");
      out.write("									<small class=\"text-muted\">&#9733; &#9733; &#9733; &#9733; &#9734;</small>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-lg-3 mb-4\">\r\n");
      out.write("							<div class=\"card h-100\">\r\n");
      out.write("								<a href=\"#\">\r\n");
      out.write("									<img class=\"card-img-top\" src=\"img/products/iphone.png\" alt=\"Sản phẩm thiết bị\"\r\n");
      out.write("										height=500rem;>\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<h4 class=\"card-title\">\r\n");
      out.write("										<a href=\"#\">IPhone 14 Pro Max</a>\r\n");
      out.write("									</h4>\r\n");
      out.write("									<h5>21.200.000</h5>\r\n");
      out.write("									<p class=\"card-text\">Sang trọng, đa dạng, độ bền tốt, tinh xảo trong từng chi\r\n");
      out.write("										tiết.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-footer\">\r\n");
      out.write("									<small class=\"text-muted\">&#9733; &#9733; &#9733; &#9733; &#9734;</small>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-lg-3 mb-4\">\r\n");
      out.write("							<div class=\"card h-100\">\r\n");
      out.write("								<a href=\"#\">\r\n");
      out.write("									<img class=\"card-img-top\" src=\"img/products/tainghe.png\" alt=\"Sản phẩm phụ kiện\"\r\n");
      out.write("										height=500rem;>\r\n");
      out.write("								</a>\r\n");
      out.write("								<div class=\"card-body\">\r\n");
      out.write("									<h4 class=\"card-title\">\r\n");
      out.write("										<a href=\"#\">Tai Nghe</a>\r\n");
      out.write("									</h4>\r\n");
      out.write("									<h5>7.200.000</h5>\r\n");
      out.write("									<p class=\"card-text\">Âm thanh sống động, chống nước, độ bền tuyết đối, năng\r\n");
      out.write("										lượng lâu dài.</p>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-footer\">\r\n");
      out.write("									<small class=\"text-muted\">&#9733; &#9733; &#9733; &#9733; &#9734;</small>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</section>\r\n");
      out.write("		<!-- End Page Content -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- MDB -->\r\n");
      out.write("	<script type=\"text/javascript\" src=\"");
      out.print(url);
      out.write("/js/mdb.umd.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
