/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-03-26 14:48:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menuleft_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Menu Left</title>\r\n");

String url = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
		+ request.getContextPath();

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(url);
      out.write("/css/mdb.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container-fluid mt-3\">\r\n");
      out.write("		<div class=\"list-group\">\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-dark\">Danh Mục Sản Phẩm</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Điện Thoại & Phụ Kiện</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Máy Ảnh & Quay Phim</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Máy Tính & Laptop</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Thời Trang Nam</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Thời Trang Nữ</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Giày Dép Nữ</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Giày Dép Nam</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Mẹ & Bé</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Thời Trang Trẻ Em</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Đồng hồ</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Phụ Kiện & Trang Sức Nữ</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Ô Tô & Xe Máy & Xe Đạp</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Túi Ví Nữ</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Sức Khỏe</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Vourcher & Dịch Vụ</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Giặt Giũ & Chăm Sóc Nhà\r\n");
      out.write("				Cửa</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Nhà Sách Online</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Chăm Sóc Thú Cưng</a>\r\n");
      out.write("			<a href=\"#\" class=\"list-group-item list-group-item-action\">Dụng Cụ & Thiết Bị Tiện\r\n");
      out.write("				Ích</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- MDB -->\r\n");
      out.write("	<script type=\"text/javascript\" src=\"");
      out.print(url);
      out.write("/js/mdb.umd.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
